# ----
# Site

title: Astro City Mini Custom Firmware
url: "https://acm-cfw.github.io/"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Astro City Mini Custom Firmware documentation.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Astro City Mini Custom Firmware
  links:
    - https://github.com/ACM-CFW

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude: 
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release


types:
  - minor
  - major
  - documentation

labels:
  - wip
  - tbd
  - stable

markdown: kramdown
